[tool.ruff]
    line-length = 120

[tool.ruff.format]
    quote-style = 'single'

[tool.ruff.lint]
    extend-select = ['I']
    ignore = ['E402']

[tool.ruff.lint.mccabe]
    max-complexity = 12

[tool.ruff.lint.isort]
    combine-as-imports = true

[tool.pytest]
    testpaths = 'tests'
    timeout = 10

[tool.coverage.run]
    source = ['pdf']
    branch = true

[tool.coverage.report]
    precision = 2
    exclude_lines = [
        'pragma: no cover',
        'raise NotImplementedError',
    ]

[tool.distutils.bdist_wheel]
    python-tag = 'py311'
