name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        sudo apt install libjpeg62 libc6
        make install
        pip freeze

    - name: test
      run: |
        chmod +x /home/runner/work/pydf/pydf/pydf/bin/wkhtmltopdf
        make lint
        make test
        make benchmark
        python -c "import pydf; print(pydf.get_version())"

    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)

  deploy:
    needs:
      - test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: install
        run: |
          pip install -U pip setuptools wheel twine
          pip install .
      - name: set version
        run: VERSION_PATH='pydf/version.py' python <(curl -Ls https://git.io/JT3rm)

      - run: python setup.py sdist bdist_wheel

      - run: twine check dist/*

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
